dj4/test_django4/app_auth/urls.py
from django.conf.urls import url

from . import views
app_name = "app_auth"
urlpatterns = [

    url(r'^$', views.Index.as_view(), name="index"),
    url(r'^login/$', views.Login.as_view(), name="login"),
    url(r'^register/$', views.Register.as_view(), name="register"),
    url(r'^member_active/$', views.MemberActive.as_view(), name="member_actice"),
    url(r'^logout/$', views.Logout.as_view(), name="logout"),
    url(r'^change_password/$', views.ChangePassword.as_view(), name="change_password"),
    url(r'^reset_password/$', views.ResetPassword.as_view(), name="reset_password"),
    url(r'^reset_password_r/$', views.ResetPasswordR.as_view(), name="reset_password_r"),
    url(r'^change_email/$', views.ChangeEmail.as_view(), name="change_email"),
    url(r'^user_edit/$', views.UserEdit.as_view(), name="user_edit"),
    url(r'^user_followed/(?P<username>.*)$', views.UserFollowed.as_view(), name="user_followed"),
    url(r'^follower_list/(?P<username>.*)&(?P<follow>.*)$', views.FollowerList.as_view(), name="follower_list"),



]

dj4/test_django4/test_django4/urls.py
from django.conf.urls import url, include
from django.contrib import admin



urlpatterns = [

    url(r'^admin/', admin.site.urls),
    url(r'^app_auth/', include('app_auth.urls', namespace="app_auth")),
    url(r'^app_article/', include('app_article.urls', namespace="app_article")),


]

dj4/test_django4/templates/temp_auth/change_email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>欢迎来到修改邮箱页面</h1>
    <form action="{% url 'app_auth:change_email' %}" method="post">
        {% csrf_token %}
        <div>
            <span>请输入当前使用邮箱：</span>
            <input type="text" name="current_email">
        </div>
        <div>
            <span>请输入新邮箱：</span>
            <input type="text" name="new_email">
        </div>
        <div>
            <input type="submit" value="提交">
        </div>
    </form>

</body>
</html>

dj4/test_django4/templates/temp_auth/change_password.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>欢迎来到密码修改页面</h1>
    <form action="{% url 'app_auth:change_password' %}" method="post">
        {% csrf_token %}
        <div>

            <span>请输入当前账号密码：</span><input type="password" name="current_password">
        </div>
        <div>

            <span>请输入新密码：</span><input type="password" name="new_password">
        </div>
        <div>

            <span>请确认输入新密码：</span><input type="password" name="re_new_password">
        </div>
        <div>

            <input type="submit" value="提交">
        </div>
    </form>
</body>
</html>

dj4/test_django4/templates/temp_auth/follower_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {% for follow in follow_list %}

        <li>{{ follow.0 }}</li>

    {% endfor %}
    <hr>
    {% for be_follow in be_follow_list %}
            <li>{{ be_follow.0 }}</li>
    {% endfor %}


</body>
</html>

dj4/test_django4/templates/temp_auth/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>欢迎来到客户主页面</h1>
    <div>
        <a href="{% url 'app_auth:login' %}">登录</a>
        <a href="{% url 'app_auth:register' %}">注册</a>
    </div>
    <div></div>

</body>
</html>

dj4/test_django4/templates/temp_auth/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>欢迎来到用户登录页面</h1>
    <form action="{% url 'app_auth:login' %}" method="post">
        {% csrf_token %}
        <div>
            <span>用户名：</span>
            <input type="text" name="username">
        </div>
        <div>
            <span>密码：</span>
            <input type="password" name="password">
        </div>
        <div>
            <input type="submit" value="提交">
        </div>
    </form>
    <a href="{% url 'app_auth:index' %}">返回主页</a>


    {% if  user.is_authenticated %}
        <a href="{% url 'app_auth:logout' %}">退出登录</a>
        <a href="{% url 'app_auth:change_password' %}">修改密码</a>
        <a href="{% url 'app_auth:change_email' %}">修改邮箱</a>
        <a href="{% url 'app_auth:user_edit' %}">个人资料</a>
        {% else %}
            <a href="{% url 'app_auth:reset_password' %}">忘记密码</a>
    {% endif %}
    <a href="{% url 'app_article:index' %}">文章首页</a>
</body>
</html>

dj4/test_django4/templates/temp_auth/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>欢迎来到用户注册页面</h1>
    <form action="{% url 'app_auth:register' %}" method="post">
        {% csrf_token %}
        <div>
            <span>用户名：</span><input type="text" name="username">
        </div>
        <div>
            <span>密码：</span><input type="password" name="password">
        </div>
        <div>
            <span>确认密码：</span><input type="password" name="re_password">
        </div>
        <div>
            <span>邮箱：</span><input type="text" name="email">
        </div>
        <div>
            <input type="submit" value="提交">
        </div>
    </form>

    <a href="{% url 'app_auth:index' %}">返回主页</a>
</body>
</html>

dj4/test_django4/templates/temp_auth/reset_password.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>欢迎来到重置密码页面</h1>
<div>
    <form action="{% url 'app_auth:reset_password' %}" method="post">
        {% csrf_token %}
        <span>请输入您的邮箱：</span>
        <input type="text" name="email">
        <input type="submit" value="提交">
    </form>
</div>

</body>
</html>

dj4/test_django4/templates/temp_auth/reset_password_r.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>欢迎来到重置密码页面</h1>
    <form action="{% url 'app_auth:reset_password_r' %}" method="post">
        {% csrf_token %}
        <div hidden>
            <span>用户名：</span>
            <input type="text" value="{{ username }}" name="username">
        </div>
        <div>
            <span>请设置密码：</span>
            <input type="password" name="password">
        </div>
        <div>
            <span>再次输入密码：</span>
            <input type="password" name="re_password">
        </div>
        <div>
            <input type="submit" value="提交">
        </div>
    </form>

</body>
</html>

dj4/test_django4/templates/temp_auth/user_edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>欢迎来到用户编辑个人信息页面</h1>
    <form action="{% url 'app_auth:user_edit' %}" method="post">
        {% csrf_token %}


        <div>
            <span>电话号码：</span>
            <input type="text" name="phone" value="{{ user_obj.userinfo.phone }}">
        </div>
        <div>
            <span>地址：</span>
            <input type="text" name="address" value="{{ user_obj.userinfo.address }}">
        </div>
        <div>
            <span>个人简介：</span>
            <textarea cols=20 rows=5 name="about_me" >{{ user_obj.userinfo.about_me }}</textarea>
        </div>
        <div>

            <input type="submit" value="提交">
        </div>
    </form>
</body>
</html>