dj4/test_django4/app_article/urls.py
from django.conf.urls import url
from . import views

app_name = "app_article"

urlpatterns = [


    url(r'^$', views.Index.as_view(), name="index"),
    url(r'^user_articles/(.*)/$', views.UserArticles.as_view(), name="user_articles"),
    url(r'^user_article/(\d+)/$', views.UserArticle.as_view(), name="user_article"),
    url(r'^article_manage/$', views.ArticleManage.as_view(), name="article_manage"),
    url(r'^article_edit/(?P<id>\d+)&(?P<username>.*)$', views.ArticleEdit.as_view(), name="article_edit"),
    url(r'^article_edit1/$', views.ArticleEdit.as_view(), name="article_edit1"),
    url(r'^followed_user_article_list/$', views.FollowedUserArticleList.as_view(), name="followed_user_article_list"),
    url(r'^article_comment/$', views.ArticleComment.as_view(), name="article_comment"),

]

dj4/test_django4/app_auth/urls.py
from django.conf.urls import url

from . import views
app_name = "app_auth"
urlpatterns = [

    url(r'^$', views.Index.as_view(), name="index"),
    url(r'^login/$', views.Login.as_view(), name="login"),
    url(r'^register/$', views.Register.as_view(), name="register"),
    url(r'^member_active/$', views.MemberActive.as_view(), name="member_actice"),
    url(r'^logout/$', views.Logout.as_view(), name="logout"),
    url(r'^change_password/$', views.ChangePassword.as_view(), name="change_password"),
    url(r'^reset_password/$', views.ResetPassword.as_view(), name="reset_password"),
    url(r'^reset_password_r/$', views.ResetPasswordR.as_view(), name="reset_password_r"),
    url(r'^change_email/$', views.ChangeEmail.as_view(), name="change_email"),
    url(r'^user_edit/$', views.UserEdit.as_view(), name="user_edit"),
    url(r'^user_followed/(?P<username>.*)$', views.UserFollowed.as_view(), name="user_followed"),
    url(r'^follower_list/(?P<username>.*)&(?P<follow>.*)$', views.FollowerList.as_view(), name="follower_list"),



]

dj4/test_django4/test_django4/urls.py
from django.conf.urls import url, include
from django.contrib import admin



urlpatterns = [

    url(r'^admin/', admin.site.urls),
    url(r'^app_auth/', include('app_auth.urls', namespace="app_auth")),
    url(r'^app_article/', include('app_article.urls', namespace="app_article")),


]

dj4/test_django4/templates/temp_article/article_edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>欢迎来到编辑文章页面</h1>
    <form action="{% url 'app_article:article_edit1' %}" method="post">
        {% csrf_token %}

        <input type="text" name="username" value="{{ article.user.username }}" hidden>
        <input type="text" name="article_id" value="{{ article.id }}" hidden>
        <textarea name="content" id="" cols="80" rows="20">{{ article.content }}</textarea>
        <div>
            <input type="submit" value="提交">
        </div>
    </form>
</body>
</html>

dj4/test_django4/templates/temp_article/article_manage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>欢迎来到文章管理页面</h1>
    {% for article in articles %}

        <p>{{ article.publish_time }}</p>
        <p>{{ article.content }}</p> <a href="{% url 'app_article:article_edit' id=article.id username=article.user.username %}">编辑文章</a>
        <hr>

    {% endfor %}
    {{ p }}
</body>
</html>

dj4/test_django4/templates/temp_article/followed_user_article_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>您关注用户的文字列表</h1>

    {% for user in users_list %}

    <div>
        {% for article in user.article.all %}
            <span>用户：<a href="{% url 'app_article:user_articles' user.username %}">{{ user.username}}</a></span>
            <span>发布时间：{{article.publish_time }}</span>
            <p>文章内容: <a href="{% url 'app_article:user_article' article.id %}">{{ article.content|truncatechars:20 }}</a></p>
            <hr>
        {% endfor %}
    </div>

    {% endfor %}
</body>
</html>

dj4/test_django4/templates/temp_article/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <a href="{% url 'app_auth:login' %}">返回登陆页</a>
    <h1>欢迎来到文章主页</h1>
    {% if mk_user %}
        <h1><a href="{% url 'app_article:article_manage' %}">文章管理</a></h1>
        <h2><a href="{% url 'app_article:followed_user_article_list' %}">您关注的用户的文章列表</a></h2>
    {% endif %}
    <form action="{% url 'app_article:index' %}" method="post">
        {% csrf_token %}
        <textarea name="content" cols="80" rows="5" placeholder="请输入您想发布的内容..."></textarea>
        <input type="submit" value="发布">
    </form>

    {% if not mk_user %}
        <h1>请先登录账号再发布文章</h1>
        <h1>
            <span>----></span> <a href="{% url 'app_auth:login' %}">登录</a>
        </h1>
    {% endif %}
    {% for article in articles %}
    <div>
        <span>用户：<a href="{% url 'app_article:user_articles' article.user.username %}">{{ article.user.username}}</a></span>
        <span>发布时间：{{ article.publish_time }}</span>

        <p>文章内容: <a href="{% url 'app_article:user_article' article.id %}">{{ article.content|truncatechars:20 }}</a></p>
        <span><a href="{% url 'app_article:user_article' article.id %}">评论</a></span>
        <hr>
    </div>
        <hr>
    {% endfor %}



    {{ p }}













</body>
</html>

dj4/test_django4/templates/temp_article/user_article.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>欢迎来到单个文章页面</h1>
    <p>{{ article.content }}</p>


    <form action="{% url 'app_article:article_comment' %}" method="post">
        {% csrf_token %}
        <input type="text" name="id" value="{{ article.id }}" readonly hidden>
        <textarea name="comment" id="" cols="80" rows="10"></textarea>
        <input type="submit" value="提交评论">
    </form>

    <h2>显示评论</h2>
    {% for comment in comment_list %}

         <div>{{ comment.comment_content }}</div>
         <div>
             评论人: <a href="{% url 'app_article:user_articles' comment.comment_user.username%}">{{ comment.comment_user.username }}</a>
         </div>
        <hr>

    {% endfor %}



</body>
</html>

dj4/test_django4/templates/temp_article/user_articles.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>欢迎来到{{ user_obj.username }}文章列表页面</h1>
<br>

<div>用户名：{{ user_obj.username }}</div>
<div>邮箱：{{ user_obj.email }}</div>
<span><a href="{% url 'app_auth:follower_list' username=user_obj.username follow=1 %}">关注了:{{ user_obj.followed.count }}人</a></span>
<span><a href="{% url 'app_auth:follower_list' username=user_obj.username follow=0 %}">被关注了：{{ user_obj.be_followed.count }}人</a></span>
{% if user == user_obj %}
    <span><a href="#" hidden>关注你</a></span>
    {% else %}
        <span><a href="{% url 'app_auth:user_followed' username=user_obj.username %}">关注你</a></span>
    {% if user.is_authenticated %}

        {% else %}
            <span><a href="{% url 'app_auth:login' %}">登录</a></span>
    {% endif %}
{% endif %}
<hr>
{% for article in articles %}
    <div>
        <span>用户：<a href="{% url 'app_article:user_articles' article.user.username %}">{{ article.user.username}}</a></span>
        <span>发布时间：{{ article.publish_time }}</span>
        <p>文章内容: <a href="{% url 'app_article:user_article' article.id %}">{{ article.content|truncatechars:20 }}</a></p>

        <hr>
    </div>
{% endfor %}

</body>
</html>